apiVersion: v1
kind: Service
metadata:
  name: desafio-k8s-go-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: desafio-k8s-go
