apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: desafio-nginx
  template:
    metadata:
      labels:
        app: desafio-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.17-alpine
          ports:
            - containerPort: 80

          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-index
              readOnly: true

      volumes:
        - name: nginx-index
          configMap:
            name: nginx-index
            items:
              - key: index.html
                path: index.html
